//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class ChucNang : BaseObject
    {
        string fMaChucNang;
        [DevExpress.Xpo.DisplayName(@"Mã chức năng")]
        public string MaChucNang
        {
            get { return fMaChucNang; }
            set { SetPropertyValue<string>("MaChucNang", ref fMaChucNang, value); }
        }
        string fTenChucNang;
        [DevExpress.Xpo.DisplayName(@"Chức năng")]
        public string TenChucNang
        {
            get { return fTenChucNang; }
            set { SetPropertyValue<string>("TenChucNang", ref fTenChucNang, value); }
        }
        ChucNang fChucNangCha;
        [Association(@"ChucNangReferencesChucNang")]
        [DevExpress.Xpo.DisplayName(@"Chức năng cha")]
        public ChucNang ChucNangCha
        {
            get { return fChucNangCha; }
            set { SetPropertyValue<ChucNang>("ChucNangCha", ref fChucNangCha, value); }
        }
        [Association(@"ChucNangReferencesChucNang"), Aggregated]
        public XPCollection<ChucNang> ChucNangCollection { get { return GetCollection<ChucNang>("ChucNangCollection"); } }
        [Association(@"PhanQuyenReferencesChucNang"), Aggregated]
        public XPCollection<PhanQuyen> PhanQuyens { get { return GetCollection<PhanQuyen>("PhanQuyens"); } }
    }

}
