//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class DanToc : BaseObject
    {
        string fTenDanToc;
        [DevExpress.Xpo.DisplayName(@"Dân tộc")]
        public string TenDanToc
        {
            get { return fTenDanToc; }
            set { SetPropertyValue<string>("TenDanToc", ref fTenDanToc, value); }
        }
    }

}
