//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class DonVi : BaseObject
    {
        int fStt;
        public int Stt
        {
            get { return fStt; }
            set { SetPropertyValue<int>("Stt", ref fStt, value); }
        }
        string fMaDonVi;
        [DevExpress.Xpo.DisplayName(@"Mã đơn vị")]
        public string MaDonVi
        {
            get { return fMaDonVi; }
            set { SetPropertyValue<string>("MaDonVi", ref fMaDonVi, value); }
        }
        string fTenDonVi;
        [DevExpress.Xpo.DisplayName(@"Đơn vị")]
        public string TenDonVi
        {
            get { return fTenDonVi; }
            set { SetPropertyValue<string>("TenDonVi", ref fTenDonVi, value); }
        }
        NienKhoa fNienKhoa;
        [Association(@"DonViReferencesNienKhoa")]
        [DevExpress.Xpo.DisplayName(@"Niên khóa")]
        public NienKhoa NienKhoa
        {
            get { return fNienKhoa; }
            set { SetPropertyValue<NienKhoa>("NienKhoa", ref fNienKhoa, value); }
        }
        TinhThanh fTinhDoan;
        [Association(@"DonViReferencesTinhThanh")]
        [DevExpress.Xpo.DisplayName(@"Tỉnh đoàn")]
        public TinhThanh TinhDoan
        {
            get { return fTinhDoan; }
            set { SetPropertyValue<TinhThanh>("TinhDoan", ref fTinhDoan, value); }
        }
        HuyenQuan fHuyenDoan;
        [Association(@"DonViReferencesHuyenQuan")]
        [DevExpress.Xpo.DisplayName(@"Huyện đoàn")]
        public HuyenQuan HuyenDoan
        {
            get { return fHuyenDoan; }
            set { SetPropertyValue<HuyenQuan>("HuyenDoan", ref fHuyenDoan, value); }
        }
        string fGhiChu;
        [DevExpress.Xpo.DisplayName(@"Ghi chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
        [Association(@"ChiDoanReferencesDonVi"), Aggregated]
        public XPCollection<ChiDoan> ChiDoans { get { return GetCollection<ChiDoan>("ChiDoans"); } }
    }

}
