//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class HuyenQuan : BaseObject
    {
        string fMaHuyenQuan;
        [DevExpress.Xpo.DisplayName(@"Mã huyện/quận")]
        public string MaHuyenQuan
        {
            get { return fMaHuyenQuan; }
            set { SetPropertyValue<string>("MaHuyenQuan", ref fMaHuyenQuan, value); }
        }
        string fTenHuyenQuan;
        [DevExpress.Xpo.DisplayName(@"Huyện/Quận")]
        public string TenHuyenQuan
        {
            get { return fTenHuyenQuan; }
            set { SetPropertyValue<string>("TenHuyenQuan", ref fTenHuyenQuan, value); }
        }
        TinhThanh fTinhThanh;
        [Association(@"HuyenQuanReferencesTinhThanh")]
        [DevExpress.Xpo.DisplayName(@"Tỉnh/Thành phố")]
        public TinhThanh TinhThanh
        {
            get { return fTinhThanh; }
            set { SetPropertyValue<TinhThanh>("TinhThanh", ref fTinhThanh, value); }
        }
        [Association(@"XaPhuongReferencesHuyenQuan"), Aggregated]
        public XPCollection<XaPhuong> XaPhuongs { get { return GetCollection<XaPhuong>("XaPhuongs"); } }
        [Association(@"DonViReferencesHuyenQuan"), Aggregated]
        public XPCollection<DonVi> DonVis { get { return GetCollection<DonVi>("DonVis"); } }
    }

}
