//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class TinhThanh : BaseObject
    {
        string fMaTinhThanh;
        [DevExpress.Xpo.DisplayName(@"Mã tỉnh/thành phố")]
        public string MaTinhThanh
        {
            get { return fMaTinhThanh; }
            set { SetPropertyValue<string>("MaTinhThanh", ref fMaTinhThanh, value); }
        }
        string fTenTinhThanh;
        [DevExpress.Xpo.DisplayName(@"Tỉnh/Thành phố")]
        public string TenTinhThanh
        {
            get { return fTenTinhThanh; }
            set { SetPropertyValue<string>("TenTinhThanh", ref fTenTinhThanh, value); }
        }
        [Association(@"HuyenQuanReferencesTinhThanh"), Aggregated]
        public XPCollection<HuyenQuan> HuyenQuans { get { return GetCollection<HuyenQuan>("HuyenQuans"); } }
        [Association(@"DonViReferencesTinhThanh"), Aggregated]
        public XPCollection<DonVi> DonVis { get { return GetCollection<DonVi>("DonVis"); } }
    }

}
