//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class TrinhDoChuyenMon : BaseObject
    {
        string fTenTrinhDoChuyenMon;
        [DevExpress.Xpo.DisplayName(@"Trình độ chuyên môn")]
        public string TenTrinhDoChuyenMon
        {
            get { return fTenTrinhDoChuyenMon; }
            set { SetPropertyValue<string>("TenTrinhDoChuyenMon", ref fTenTrinhDoChuyenMon, value); }
        }
    }

}
