//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class TrinhDoLyLuanChinhTri : BaseObject
    {
        string fTenTrinhDoLyLuanChinhTri;
        [DevExpress.Xpo.DisplayName(@"Trình độ lý luận chính trị")]
        public string TenTrinhDoLyLuanChinhTri
        {
            get { return fTenTrinhDoLyLuanChinhTri; }
            set { SetPropertyValue<string>("TenTrinhDoLyLuanChinhTri", ref fTenTrinhDoLyLuanChinhTri, value); }
        }
    }

}
