//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class TrinhDoNgoaiNgu : BaseObject
    {
        string fTenTrinhDoNgoaiNgu;
        [DevExpress.Xpo.DisplayName(@"Trình độ ngoại ngữ")]
        public string TenTrinhDoNgoaiNgu
        {
            get { return fTenTrinhDoNgoaiNgu; }
            set { SetPropertyValue<string>("TenTrinhDoNgoaiNgu", ref fTenTrinhDoNgoaiNgu, value); }
        }
    }

}
