//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Lpnt.DuLieu
{

    public partial class XaPhuong : BaseObject
    {
        string fMaXaPhuong;
        [DevExpress.Xpo.DisplayName(@"Mã xã/phường")]
        public string MaXaPhuong
        {
            get { return fMaXaPhuong; }
            set { SetPropertyValue<string>("MaXaPhuong", ref fMaXaPhuong, value); }
        }
        string fTenXaPhuong;
        [DevExpress.Xpo.DisplayName(@"Xã/Phường")]
        public string TenXaPhuong
        {
            get { return fTenXaPhuong; }
            set { SetPropertyValue<string>("TenXaPhuong", ref fTenXaPhuong, value); }
        }
        HuyenQuan fHuyenQuan;
        [Association(@"XaPhuongReferencesHuyenQuan")]
        [DevExpress.Xpo.DisplayName(@"Huyện/Quận")]
        public HuyenQuan HuyenQuan
        {
            get { return fHuyenQuan; }
            set { SetPropertyValue<HuyenQuan>("HuyenQuan", ref fHuyenQuan, value); }
        }
    }

}
